name: C/C++ CI for iOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest 
    # Use macOS for iOS compatibility

    steps:
    # Step 1: Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Step 2: Install dependencies for iOS
    - name: Install Dependencies
      run: |
        brew update
        brew install automake autoconf libtool
        xcode-select --install 
    # Install Xcode Command Line Tools

    # Step 3: Configure the build for iOS
    - name: Configure for iOS
      run: |
        ./configure --host=arm64-apple-darwin --enable-ios 
    # Adjust flags as needed

    # Step 4: Build the project
    - name: Build Project
      run: make

    # Step 5: Run tests
    - name: Run Tests
      run: make check

    # Step 6: Package the build
    - name: Package Build
      run: make dist

  deploy:
    needs: build
    runs-on: macos-latest 
   # Use macOS for deployment

    steps:
    # Step 1: Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Step 2: Upload build artifacts
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build-artifacts
        path: idevice/.github/workflows/
    # Adjust the path if necessary

    # Step 3: Deploy the application
    - name: Deploy Application
      run: |
        echo 
        - name: Deploy Application
          uses: actions/deploy@v4
          path: idevice/.github/workflows/
